services:
  lnbits:
    container_name: lnbits
    image: lnbits/lnbits
    volumes:
      - ./.env:/app/.env
      - ~/data/lnbits/data:/app/data
    ports:
      - "5000:5000"
    environment:
      LNBITS_EXTENSIONS_PATH: "/app/data/extensions"
  cloudflared:
    container_name: lnbits-cloudflare-tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel --url http://lnbits:5000
